package com.workspace.server.dao

import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id
import javax.persistence.Table
import javax.validation.constraints.NotNull


/**
 * Created by CHENMA11 on 12/29/2017.
 */
@Entity
@Table(name = "user")
public class User {
    // ==============
    // PRIVATE FIELDS
    // ==============
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    long id;
    // The user email
    @NotNull
    @Column
    String email;
    // The user name
    @NotNull
    @Column
    String name;

} // class User